### ISSUE TITLE
docker healthcheck status: unhealthy

### ISSUE THREAD

**Issue by OtharSmirnow** [devinsolutions/docker-osticket#54]
Hi,

healthcheck fails - curl request returns 400

curl request:
```
/var/www/html # curl -fIsS http://localhost/
HTTP/1.1 400 Bad Request
Server: nginx
Date: Thu, 09 Nov 2023 09:53:41 GMT
Content-Type: text/html; charset=UTF-8
Content-Length: 23
Connection: keep-alive
Set-Cookie: OSTSESSID=vda754cu6u7vc4pu881vcop36e; expires=Thu, 09-Nov-2023 10:17:41 GMT; Max-Age=1440; path=/; HttpOnly
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block

curl: (22) The requested URL returned error: 400
/var/www/html # curl -fIsS https://localhost/
curl: (7) Failed to connect to localhost port 443 after 0 ms: Couldn't connect to server
/var/www/html # curl -fIsS http://localhost/
HTTP/1.1 400 Bad Request
Server: nginx
Date: Thu, 09 Nov 2023 09:54:30 GMT
Content-Type: text/html; charset=UTF-8
Content-Length: 23
Connection: keep-alive
Set-Cookie: OSTSESSID=jn36u7umav1javutggsvuulkuk; expires=Thu, 09-Nov-2023 10:18:30 GMT; Max-Age=1440; path=/; HttpOnly
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block

curl: (22) The requested URL returned error: 400
```

compose file:
```
version: '3.7'

services:
  osticket:
    image: devinsolutions/osticket
    container_name: osticket
    restart: unless-stopped
    volumes:
      - www:/www/osticket
      - logs:/www/logs
    environment:
      - MYSQL_HOST=osticket_db
      - MYSQL_ROOT_PASSWORD=******
      - MYSQL_DATABASE=osticket
      - MYSQL_USER=osticket
      - MYSQL_PASSWORD=******
      - INSTALL_SECRET=******
  
      - TIMEZONE=Europe/Warsaw
      - CRON_INTERVAL=10
      - SMTP_HOST=******
      - SMTP_PORT=25
      - SMTP_FROM=******
      - SMTP_TLS=0
      - SMTP_USER=******
      - SMTP_PASS=password

      - INSTALL_NAME=******

      - ADMIN_FIRSTNAME=******
      - ADMIN_LASTNAME=******
      - ADMIN_EMAIL=******
    ports:
      - 8080:80
    networks:
      - osticket_network
      - waf-proxy_proxy_network
    depends_on:
      - osticket_db

  osticket_db:
    image: mariadb:latest
    container_name: osticket_db
    volumes:
      - db:/var/lib/mysql
    environment:
      - TIMEZONE=Europe/Warsaw
      - MARIADB_ROOT_PASSWORD=******
      - MARIADB_DATABASE=osticket
      - MARIADB_USER=osticket
      - MARIADB_PASSWORD=******
    restart: unless-stopped
    networks:
      - osticket_network

networks:
  osticket_network:
  waf-proxy_proxy_network:
    external: true
volumes:
  www:
  logs:
  db:
```
