### ISSUE TITLE
Subject Missing after Upgrade of 1.12 ->1.14.1

### ISSUE THREAD

**Issue by PromoFaux** [devinsolutions/docker-osticket#8]
Hi there,

Thanks for this fork... I was using CampbellSoftwareSolutions one previously, which was fine for the most part.. but after facing issues being unable to upgrade to 1.14.1, I stumbled across your fork.

So, I appear to have upgraded semi-successfully, most things appear to be working... but the subject field is missing from the ticket queue

![image](https://user-images.githubusercontent.com/1998970/75772941-cc010680-5d44-11ea-9065-16958082f51d.png)

despite the ticket actually having a subject:

![image](https://user-images.githubusercontent.com/1998970/75772963-d8855f00-5d44-11ea-9b98-0e42c7834009.png)

I've confirmed all past tickets are displaying the same behaviour.

Just wanted to check with you before I go to the osTicket forums, as it may be something specific to your image. Or could it be that the database upgrade was not so smooth?

Changing things in the Columns tab of the queue settings does not appear to persist...

![image](https://user-images.githubusercontent.com/1998970/75773333-990b4280-5d45-11ea-93ac-550f4b523661.png)

Compose file:

``` yml
version: '3.4'
services:
  mysql:
    container_name: mysql
    restart: unless-stopped
    image: mysql:5.7.22
    environment:
      MYSQL_ROOT_PASSWORD: [PASSWORD]
      MYSQL_DATABASE: osticket
      MYSQL_PASSWORD: [PASSWORD]
      MYSQL_USER: osticket
    volumes:
      - ./mysql/:/var/lib/mysql
    ports:
      - 3306:3306

  osticket:
    container_name: osticket
    restart: unless-stopped
    image: devinsolutions/osticket
    depends_on:
      - mysql
    environment:
      INSTALL_SECRET: [SECRET]
      MYSQL_HOST: mysql
      MYSQL_PASSWORD: [PASSWORD]
      CRON_INTERVAL: 1
    image: devinsolutions/osticket:1.14.1
    ports:
    - 8080:80
```
